### ISSUE TITLE
文件名重复导致Windows下操作异常

### ISSUE THREAD

**Issue by blackmatrix7** [Orz-3/mini#14]
你好

https://github.com/Orz-3/mini/blob/master/Color/Bilibili.png

https://github.com/Orz-3/mini/blob/master/Color/bilibili.png

以上两个文件

因为Windows的NTFS文件系统本身不区分文件名的大小写，所以在Clone仓库后，会因为同时存在大小写文件导致异常。

虽然使用fsutil可以解决，但是需要安装适用于Linunx的Windows子系统，有一定的操作门槛。

希望能修改其中的一个文件名，谢谢！

**Comment by Orz-3** [comment]
> 你好
> 
> https://github.com/Orz-3/mini/blob/master/Color/Bilibili.png
> 
> https://github.com/Orz-3/mini/blob/master/Color/bilibili.png
> 
> 以上两个文件
> 
> 2010年月25日，当窗、NTFS、文体、多维
> 
> 弗斯夫斯 · 乌蒂尔， 伊夫特 · 利努克斯 · 温特 · 林特斯 · 林特斯， 10 月 1 日， 文斯 · 考尔 · 林布林斯 · 考尔
> 
> 希望能修改其中的一个文件名，谢谢！

你好，这两个图标如果仅QuanX引用的话是正常的，至于Clone问题没有在考虑范围内，而且一旦更改是导致引用过的人都需要更改，所以不太方便更名

**Comment by Orz-3** [comment]
因为只考虑了QuanX的正常引用，并没有考虑Clone问题，而且更名牵连到所有正常引用过这个文件的人，所以就不考虑更名了
