### ISSUE TITLE
请教：QuanX任务仓库中任务的图片有些无法显示，请问它对图片有什么要求？

### ISSUE THREAD

**Issue by JoJoJotarou** [Orz-3/mini#22]
如题，我搜索了很久但是，找不到解决方案，而你仓库的图片都可以显示，我无法显示的[图片1](https://github.com/JoJoJotarou/myScript/blob/master/script/jd/icon/jddj.png)、[图片2](https://github.com/JoJoJotarou/myScript/blob/master/script/ximalaya/icon/ximalaya.png)、[图片3](https://github.com/JoJoJotarou/myScript/blob/master/script/meituan/icon/mall.meituan.png)

十分感谢~

**Comment by Orz-3** [comment]
144*144的png
