### ISSUE TITLE
彩色图标可以添加一个WeChat图标吗

### ISSUE THREAD

**Issue by Me-x** [Orz-3/mini#23]
一直很喜欢大佬的图标 。用了很长时间了，最近搞了WeChat分流 ，发现找不到合适的图标  。大佬有时间了。可以增加一个吗  谢谢

**Comment by Orz-3** [comment]
主要是懒，不加了吧

**Comment by Me-x** [comment]
大佬 ，我这边自己弄了弄了一个。风格和你的差不多，可以的话。能否和你的mini项目合并一下。
![](https://github.com/Me-x/QX-icon/blob/main/icon/WeChat.png)

**Comment by Me-x** [comment]
https://github.com/Me-x/QX-icon/tree/main/icon
