### ISSUE TITLE
新的机场图标增加请求

### ISSUE THREAD

**Issue by Lunaeth** [Orz-3/mini#4]
网站地址：https://gfw.center
群组头像：https://s1.ax1x.com/2020/04/14/GznmaF.png
名称来历暂无，目前是一家小型中转机场。恳请能加入图标库，再次感谢。

**Comment by Orz-3** [comment]
已收到，不过这个图标效果可能会不太理想

**Comment by Lunaeth** [comment]
您好，那请问这个改进后的图标可以吗？
https://s1.ax1x.com/2020/04/14/GzqFED.png

**Comment by Lunaeth** [comment]
您好，那请问这个改进后的图标可以吗？
https://s1.ax1x.com/2020/04/14/GzO8cn.png

**Comment by Orz-3** [comment]
我已经上传了一个版本，文件名GFW.png  你可以看一下，另可以在Telegram交流群联系我。https://t.me/Orzmini

**Comment by Lunaeth** [comment]
好的，感谢您的添加!
