### ISSUE TITLE
麻烦添加一个 BGP 图标吧

### ISSUE THREAD

**Issue by omeks** [Orz-3/mini#9]
现在有 IPLC、IEPL、AnyCast，唯独缺少 BGP。

**Comment by Orz-3** [comment]
已增加

**Comment by omeks** [comment]
> 已增加

感谢大佬

**Comment by omeks** [comment]
大佬你是不是忘记上传了 只看到README示例图里有 但是没看到图片文件 😂

**Comment by Orz-3** [comment]
哦哦，图标效果还不太理想，昨晚太晚了没改完，今天又耽搁了，晚些我回去再改

**Comment by omeks** [comment]
> 哦哦，图标效果还不太理想，昨晚太晚了没改完，今天又耽搁了，晚些我回去再改

好的，大佬辛苦了！
